### ISSUE TITLE
Änderungswünsche Version 3.1.

### ISSUE THREAD

**Issue by janbaumanninfoclio** [nchachereau/csl-style-for-infoclio-ch#1]
Sammelbandbeitrag/Contribution dans un recueil: Wenn die Autorin des Kapitels die gleiche ist wie die Herausgeberin des Buchs bzw. die Autorin des Buchs, dann ist es doch eigentlich üblich "Ders." bzw. "Dies." zu verwenden.

Beispiel:
Blum, Hester: Dead Letter Reckoning, in: Dies.: The News at the Ends of the Earth. The Print Culture of Polar Exploration, 2019, S. 177–208. Online: <https://muse.jhu.edu/pub/4/oa_monograph/chapter/2316075>, Stand: 14.03.2024.

Das Problem wird aber sein, dass Zotero ja nicht zwischen Autorin und Autor unterscheiden kann und deshalb nicht weiss, ob "Dies." oder "Ders." ausgegeben werden soll. Gibt es dafür eine Lösung? Oder ist es deiner Meinung nach besser wenn wir es lassen wie es ist?

**Comment by nchachereau** [comment]
Danke für den Vorschlag. Das Hauptproblem liegt darin, dass ich nicht im [CSL-Standard](https://docs.citationstyles.org/en/stable/specification.html) nichts gefunden habe, um so etwas zu ermöglichen. Name von Autor oder Autorin kann in der Bibliographie wegfallen, wenn andere Arbeiten derselben Person gleich vorher erwähnt worden sind («[Reference Grouping](https://docs.citationstyles.org/en/stable/specification.html#reference-grouping)»). Die Möglichkeit, einen Name durch etwas anderes zu ersetzen, wenn der Name im selben Verweis schon erwähnt worden ist, scheint es nicht zu geben. Und dann käme noch das Problem des Genders dieser Person, wie du richtig schreibst.

**Comment by janbaumanninfoclio** [comment]
Merci für die Erklärung. Ja, ich denke dann lassen wir das besser so wie es ist.
